debug: true
spring:
  freemarker:
    charset: UTF-8
    cache: false
    check-template-location: true
    content-type: text/html
    template-loader-path: classpath:/templates/
    suffix: .ftl
    enabled: true
  output:
    ansi:
      enabled: detect
  mvc:
    favicon:
      enabled: false

server:
  compression:
    enabled: true
  port: 8070
  tomcat:
    accesslog:
      enabled: true
